language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-express' ]; then cd .. && eval "mv $currentfolder generator-ng-express" && cd generator-ng-express; fi

